### ISSUE TITLE
Have you update the Templates to Next 13 ?

### ISSUE THREAD

**Issue by jameswong3388** [davidivkovic/tailwindui#1]

**Comment by davidivkovic** [comment]
Hey, this is just a nulled of the official TailwindUI package. It was last updated in September. You can see the changelog here: https://tailwindui.com/changelog

Once they make an update I will update it too.

**Comment by jameswong3388** [comment]
Hi @davidivkovic, They recently updated their NextJs version for the templates to 13. Maybe you can check it out. 
Thx!

**Comment by davidivkovic** [comment]
I will look into it, but I can't promise anything soon, Thank you James! 😁

**Comment by jameswong3388** [comment]
No problem, thx for your contribution!
